name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm (Bun uses .npmrc too)
      - uses: oven-sh/setup-bun@v1 # Use the official setup-bun action [1, 3, 4, 5]
        with:
          bun-version: 'latest' # You can specify a version like '1.x' or '1.0.0'
          registry-url: 'https://registry.npmjs.org'
      - run: bun ci # Equivalent to npm ci for reproducible installs [2, 12]
      - run: bun publish --provenance --access public # Bun has a direct publish command [7, 9]
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}